SOURCES=\
src/FileReader.cpp\
src/MolSim.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/VTKWriter.cpp\
src/outputWriter/XYZWriter.cpp\
src/io/InputHandler.cpp\
src/io/OutputHandler.cpp\
src/io/ParticlesInput.cpp\
src/io/input.cpp\
src/io/XMLInput.cpp\
src/io/VTKOutput.cpp\
src/io/XYZOutput.cpp\
src/ParticleContainer.cpp\
src/ParticleContainerLC.cpp\
src/BoundaryConds.cpp\
src/DynamicsCalc.cpp\
src/Particle.cpp\
src/forces/ForceHandler.cpp\
src/forces/Gravitation.cpp\
src/forces/EarthGravitation.cpp\
src/forces/LennardJones.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/ParticleGenerator.cpp\
src/test/ParticleContainerTest.cpp\
src/test/ParticleContainerLCTest.cpp\
src/test/LennardJonesTest.cpp\
src/test/ParticleGeneratorTest.cpp\
src/test/XMLInputTest.cpp\
