// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "input.h"

namespace input
{
  // decimalvector
  // 

  const decimalvector::x_type& decimalvector::
  x () const
  {
    return this->x_.get ();
  }

  decimalvector::x_type& decimalvector::
  x ()
  {
    return this->x_.get ();
  }

  void decimalvector::
  x (const x_type& x)
  {
    this->x_.set (x);
  }

  const decimalvector::y_type& decimalvector::
  y () const
  {
    return this->y_.get ();
  }

  decimalvector::y_type& decimalvector::
  y ()
  {
    return this->y_.get ();
  }

  void decimalvector::
  y (const y_type& x)
  {
    this->y_.set (x);
  }

  const decimalvector::z_type& decimalvector::
  z () const
  {
    return this->z_.get ();
  }

  decimalvector::z_type& decimalvector::
  z ()
  {
    return this->z_.get ();
  }

  void decimalvector::
  z (const z_type& x)
  {
    this->z_.set (x);
  }


  // integervector
  // 

  const integervector::x_type& integervector::
  x () const
  {
    return this->x_.get ();
  }

  integervector::x_type& integervector::
  x ()
  {
    return this->x_.get ();
  }

  void integervector::
  x (const x_type& x)
  {
    this->x_.set (x);
  }

  const integervector::y_type& integervector::
  y () const
  {
    return this->y_.get ();
  }

  integervector::y_type& integervector::
  y ()
  {
    return this->y_.get ();
  }

  void integervector::
  y (const y_type& x)
  {
    this->y_.set (x);
  }

  const integervector::z_type& integervector::
  z () const
  {
    return this->z_.get ();
  }

  integervector::z_type& integervector::
  z ()
  {
    return this->z_.get ();
  }

  void integervector::
  z (const z_type& x)
  {
    this->z_.set (x);
  }


  // boundarytype
  // 

  boundarytype::
  boundarytype (value v)
  : ::xml_schema::string (_xsd_boundarytype_literals_[v])
  {
  }

  boundarytype::
  boundarytype (const char* v)
  : ::xml_schema::string (v)
  {
  }

  boundarytype::
  boundarytype (const ::std::string& v)
  : ::xml_schema::string (v)
  {
  }

  boundarytype::
  boundarytype (const ::xml_schema::string& v)
  : ::xml_schema::string (v)
  {
  }

  boundarytype::
  boundarytype (const boundarytype& v,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::string (v, f, c)
  {
  }

  boundarytype& boundarytype::
  operator= (value v)
  {
    static_cast< ::xml_schema::string& > (*this) = 
    ::xml_schema::string (_xsd_boundarytype_literals_[v]);

    return *this;
  }


  // molsimdata
  // 

  const molsimdata::outputbasename_type& molsimdata::
  outputbasename () const
  {
    return this->outputbasename_.get ();
  }

  molsimdata::outputbasename_type& molsimdata::
  outputbasename ()
  {
    return this->outputbasename_.get ();
  }

  void molsimdata::
  outputbasename (const outputbasename_type& x)
  {
    this->outputbasename_.set (x);
  }

  void molsimdata::
  outputbasename (::std::auto_ptr< outputbasename_type > x)
  {
    this->outputbasename_.set (x);
  }

  const molsimdata::writefreq_type& molsimdata::
  writefreq () const
  {
    return this->writefreq_.get ();
  }

  molsimdata::writefreq_type& molsimdata::
  writefreq ()
  {
    return this->writefreq_.get ();
  }

  void molsimdata::
  writefreq (const writefreq_type& x)
  {
    this->writefreq_.set (x);
  }

  const molsimdata::timestep_type& molsimdata::
  timestep () const
  {
    return this->timestep_.get ();
  }

  molsimdata::timestep_type& molsimdata::
  timestep ()
  {
    return this->timestep_.get ();
  }

  void molsimdata::
  timestep (const timestep_type& x)
  {
    this->timestep_.set (x);
  }

  const molsimdata::endtime_type& molsimdata::
  endtime () const
  {
    return this->endtime_.get ();
  }

  molsimdata::endtime_type& molsimdata::
  endtime ()
  {
    return this->endtime_.get ();
  }

  void molsimdata::
  endtime (const endtime_type& x)
  {
    this->endtime_.set (x);
  }

  const molsimdata::domain_optional& molsimdata::
  domain () const
  {
    return this->domain_;
  }

  molsimdata::domain_optional& molsimdata::
  domain ()
  {
    return this->domain_;
  }

  void molsimdata::
  domain (const domain_type& x)
  {
    this->domain_.set (x);
  }

  void molsimdata::
  domain (const domain_optional& x)
  {
    this->domain_ = x;
  }

  void molsimdata::
  domain (::std::auto_ptr< domain_type > x)
  {
    this->domain_.set (x);
  }

  const molsimdata::thermostat_type& molsimdata::
  thermostat () const
  {
    return this->thermostat_.get ();
  }

  molsimdata::thermostat_type& molsimdata::
  thermostat ()
  {
    return this->thermostat_.get ();
  }

  void molsimdata::
  thermostat (const thermostat_type& x)
  {
    this->thermostat_.set (x);
  }

  void molsimdata::
  thermostat (::std::auto_ptr< thermostat_type > x)
  {
    this->thermostat_.set (x);
  }

  const molsimdata::objectlist_type& molsimdata::
  objectlist () const
  {
    return this->objectlist_.get ();
  }

  molsimdata::objectlist_type& molsimdata::
  objectlist ()
  {
    return this->objectlist_.get ();
  }

  void molsimdata::
  objectlist (const objectlist_type& x)
  {
    this->objectlist_.set (x);
  }

  void molsimdata::
  objectlist (::std::auto_ptr< objectlist_type > x)
  {
    this->objectlist_.set (x);
  }

  const molsimdata::particleTypes_type& molsimdata::
  particleTypes () const
  {
    return this->particleTypes_.get ();
  }

  molsimdata::particleTypes_type& molsimdata::
  particleTypes ()
  {
    return this->particleTypes_.get ();
  }

  void molsimdata::
  particleTypes (const particleTypes_type& x)
  {
    this->particleTypes_.set (x);
  }

  void molsimdata::
  particleTypes (::std::auto_ptr< particleTypes_type > x)
  {
    this->particleTypes_.set (x);
  }


  // domain
  // 

  const domain::size_type& domain::
  size () const
  {
    return this->size_.get ();
  }

  domain::size_type& domain::
  size ()
  {
    return this->size_.get ();
  }

  void domain::
  size (const size_type& x)
  {
    this->size_.set (x);
  }

  void domain::
  size (::std::auto_ptr< size_type > x)
  {
    this->size_.set (x);
  }

  const domain::cutoff_type& domain::
  cutoff () const
  {
    return this->cutoff_.get ();
  }

  domain::cutoff_type& domain::
  cutoff ()
  {
    return this->cutoff_.get ();
  }

  void domain::
  cutoff (const cutoff_type& x)
  {
    this->cutoff_.set (x);
  }

  const domain::boundaries_type& domain::
  boundaries () const
  {
    return this->boundaries_.get ();
  }

  domain::boundaries_type& domain::
  boundaries ()
  {
    return this->boundaries_.get ();
  }

  void domain::
  boundaries (const boundaries_type& x)
  {
    this->boundaries_.set (x);
  }

  void domain::
  boundaries (::std::auto_ptr< boundaries_type > x)
  {
    this->boundaries_.set (x);
  }


  // thermostat
  //

  const thermostat::brownian_optional& thermostat::
  brownian () const
  {
    return this->brownian_;
  }

  thermostat::brownian_optional& thermostat::
  brownian ()
  {
    return this->brownian_;
  }

  void thermostat::
  brownian (const brownian_type& x)
  {
    this->brownian_.set (x);
  }

  void thermostat::
  brownian (const brownian_optional& x)
  {
    this->brownian_ = x;
  }

  const thermostat::inittemp_type& thermostat::
  inittemp () const
  {
    return this->inittemp_.get ();
  }

  thermostat::inittemp_type& thermostat::
  inittemp ()
  {
    return this->inittemp_.get ();
  }

  void thermostat::
  inittemp (const inittemp_type& x)
  {
    this->inittemp_.set (x);
  }

  const thermostat::starttime_type& thermostat::
  starttime () const
  {
    return this->starttime_.get ();
  }

  thermostat::starttime_type& thermostat::
  starttime ()
  {
    return this->starttime_.get ();
  }

  void thermostat::
  starttime (const starttime_type& x)
  {
    this->starttime_.set (x);
  }

  const thermostat::targettemp_type& thermostat::
  targettemp () const
  {
    return this->targettemp_.get ();
  }

  thermostat::targettemp_type& thermostat::
  targettemp ()
  {
    return this->targettemp_.get ();
  }

  void thermostat::
  targettemp (const targettemp_type& x)
  {
    this->targettemp_.set (x);
  }

  const thermostat::tempdiff_type& thermostat::
  tempdiff () const
  {
    return this->tempdiff_.get ();
  }

  thermostat::tempdiff_type& thermostat::
  tempdiff ()
  {
    return this->tempdiff_.get ();
  }

  void thermostat::
  tempdiff (const tempdiff_type& x)
  {
    this->tempdiff_.set (x);
  }

  const thermostat::interval_type& thermostat::
  interval () const
  {
    return this->interval_.get ();
  }

  thermostat::interval_type& thermostat::
  interval ()
  {
    return this->interval_.get ();
  }

  void thermostat::
  interval (const interval_type& x)
  {
    this->interval_.set (x);
  }


  // objectlist
  // 

  const objectlist::cuboid_sequence& objectlist::
  cuboid () const
  {
    return this->cuboid_;
  }

  objectlist::cuboid_sequence& objectlist::
  cuboid ()
  {
    return this->cuboid_;
  }

  void objectlist::
  cuboid (const cuboid_sequence& s)
  {
    this->cuboid_ = s;
  }

  const objectlist::sphere_sequence& objectlist::
  sphere () const
  {
    return this->sphere_;
  }

  objectlist::sphere_sequence& objectlist::
  sphere ()
  {
    return this->sphere_;
  }

  void objectlist::
  sphere (const sphere_sequence& s)
  {
    this->sphere_ = s;
  }

  const objectlist::particle_sequence& objectlist::
  particle () const
  {
    return this->particle_;
  }

  objectlist::particle_sequence& objectlist::
  particle ()
  {
    return this->particle_;
  }

  void objectlist::
  particle (const particle_sequence& s)
  {
    this->particle_ = s;
  }


  // particleTypes
  //

  const particleTypes::type_sequence& particleTypes::
  type () const
  {
    return this->type_;
  }

  particleTypes::type_sequence& particleTypes::
  type ()
  {
    return this->type_;
  }

  void particleTypes::
  type (const type_sequence& s)
  {
    this->type_ = s;
  }


  // boundaries
  // 

  const boundaries::front_type& boundaries::
  front () const
  {
    return this->front_.get ();
  }

  boundaries::front_type& boundaries::
  front ()
  {
    return this->front_.get ();
  }

  void boundaries::
  front (const front_type& x)
  {
    this->front_.set (x);
  }

  void boundaries::
  front (::std::auto_ptr< front_type > x)
  {
    this->front_.set (x);
  }

  const boundaries::back_type& boundaries::
  back () const
  {
    return this->back_.get ();
  }

  boundaries::back_type& boundaries::
  back ()
  {
    return this->back_.get ();
  }

  void boundaries::
  back (const back_type& x)
  {
    this->back_.set (x);
  }

  void boundaries::
  back (::std::auto_ptr< back_type > x)
  {
    this->back_.set (x);
  }

  const boundaries::left_type& boundaries::
  left () const
  {
    return this->left_.get ();
  }

  boundaries::left_type& boundaries::
  left ()
  {
    return this->left_.get ();
  }

  void boundaries::
  left (const left_type& x)
  {
    this->left_.set (x);
  }

  void boundaries::
  left (::std::auto_ptr< left_type > x)
  {
    this->left_.set (x);
  }

  const boundaries::right_type& boundaries::
  right () const
  {
    return this->right_.get ();
  }

  boundaries::right_type& boundaries::
  right ()
  {
    return this->right_.get ();
  }

  void boundaries::
  right (const right_type& x)
  {
    this->right_.set (x);
  }

  void boundaries::
  right (::std::auto_ptr< right_type > x)
  {
    this->right_.set (x);
  }

  const boundaries::top_type& boundaries::
  top () const
  {
    return this->top_.get ();
  }

  boundaries::top_type& boundaries::
  top ()
  {
    return this->top_.get ();
  }

  void boundaries::
  top (const top_type& x)
  {
    this->top_.set (x);
  }

  void boundaries::
  top (::std::auto_ptr< top_type > x)
  {
    this->top_.set (x);
  }

  const boundaries::bottom_type& boundaries::
  bottom () const
  {
    return this->bottom_.get ();
  }

  boundaries::bottom_type& boundaries::
  bottom ()
  {
    return this->bottom_.get ();
  }

  void boundaries::
  bottom (const bottom_type& x)
  {
    this->bottom_.set (x);
  }

  void boundaries::
  bottom (::std::auto_ptr< bottom_type > x)
  {
    this->bottom_.set (x);
  }


  // cuboid
  // 

  const cuboid::location_type& cuboid::
  location () const
  {
    return this->location_.get ();
  }

  cuboid::location_type& cuboid::
  location ()
  {
    return this->location_.get ();
  }

  void cuboid::
  location (const location_type& x)
  {
    this->location_.set (x);
  }

  void cuboid::
  location (::std::auto_ptr< location_type > x)
  {
    this->location_.set (x);
  }

  const cuboid::velocity_type& cuboid::
  velocity () const
  {
    return this->velocity_.get ();
  }

  cuboid::velocity_type& cuboid::
  velocity ()
  {
    return this->velocity_.get ();
  }

  void cuboid::
  velocity (const velocity_type& x)
  {
    this->velocity_.set (x);
  }

  void cuboid::
  velocity (::std::auto_ptr< velocity_type > x)
  {
    this->velocity_.set (x);
  }

  const cuboid::numparticles_type& cuboid::
  numparticles () const
  {
    return this->numparticles_.get ();
  }

  cuboid::numparticles_type& cuboid::
  numparticles ()
  {
    return this->numparticles_.get ();
  }

  void cuboid::
  numparticles (const numparticles_type& x)
  {
    this->numparticles_.set (x);
  }

  void cuboid::
  numparticles (::std::auto_ptr< numparticles_type > x)
  {
    this->numparticles_.set (x);
  }

  const cuboid::meshwidth_type& cuboid::
  meshwidth () const
  {
    return this->meshwidth_.get ();
  }

  cuboid::meshwidth_type& cuboid::
  meshwidth ()
  {
    return this->meshwidth_.get ();
  }

  void cuboid::
  meshwidth (const meshwidth_type& x)
  {
    this->meshwidth_.set (x);
  }

  const cuboid::mass_type& cuboid::
  mass () const
  {
    return this->mass_.get ();
  }

  cuboid::mass_type& cuboid::
  mass ()
  {
    return this->mass_.get ();
  }

  void cuboid::
  mass (const mass_type& x)
  {
    this->mass_.set (x);
  }

  const cuboid::type_optional& cuboid::
  type () const
  {
    return this->type_;
  }

  cuboid::type_optional& cuboid::
  type ()
  {
    return this->type_;
  }

  void cuboid::
  type (const type_type& x)
  {
    this->type_.set (x);
  }

  void cuboid::
  type (const type_optional& x)
  {
    this->type_ = x;
  }


  // sphere
  // 

  const sphere::location_type& sphere::
  location () const
  {
    return this->location_.get ();
  }

  sphere::location_type& sphere::
  location ()
  {
    return this->location_.get ();
  }

  void sphere::
  location (const location_type& x)
  {
    this->location_.set (x);
  }

  void sphere::
  location (::std::auto_ptr< location_type > x)
  {
    this->location_.set (x);
  }

  const sphere::velocity_type& sphere::
  velocity () const
  {
    return this->velocity_.get ();
  }

  sphere::velocity_type& sphere::
  velocity ()
  {
    return this->velocity_.get ();
  }

  void sphere::
  velocity (const velocity_type& x)
  {
    this->velocity_.set (x);
  }

  void sphere::
  velocity (::std::auto_ptr< velocity_type > x)
  {
    this->velocity_.set (x);
  }

  const sphere::numparticles_type& sphere::
  numparticles () const
  {
    return this->numparticles_.get ();
  }

  sphere::numparticles_type& sphere::
  numparticles ()
  {
    return this->numparticles_.get ();
  }

  void sphere::
  numparticles (const numparticles_type& x)
  {
    this->numparticles_.set (x);
  }

  const sphere::meshwidth_type& sphere::
  meshwidth () const
  {
    return this->meshwidth_.get ();
  }

  sphere::meshwidth_type& sphere::
  meshwidth ()
  {
    return this->meshwidth_.get ();
  }

  void sphere::
  meshwidth (const meshwidth_type& x)
  {
    this->meshwidth_.set (x);
  }

  const sphere::mass_type& sphere::
  mass () const
  {
    return this->mass_.get ();
  }

  sphere::mass_type& sphere::
  mass ()
  {
    return this->mass_.get ();
  }

  void sphere::
  mass (const mass_type& x)
  {
    this->mass_.set (x);
  }

  const sphere::sigma_type& sphere::
  sigma () const
  {
    return this->sigma_.get ();
  }

  sphere::sigma_type& sphere::
  sigma ()
  {
    return this->sigma_.get ();
  }

  void sphere::
  sigma (const sigma_type& x)
  {
    this->sigma_.set (x);
  }

  const sphere::epsilon_type& sphere::
  epsilon () const
  {
    return this->epsilon_.get ();
  }

  sphere::epsilon_type& sphere::
  epsilon ()
  {
    return this->epsilon_.get ();
  }

  void sphere::
  epsilon (const epsilon_type& x)
  {
    this->epsilon_.set (x);
  }

  const sphere::type_optional& sphere::
  type () const
  {
    return this->type_;
  }

  sphere::type_optional& sphere::
  type ()
  {
    return this->type_;
  }

  void sphere::
  type (const type_type& x)
  {
    this->type_.set (x);
  }

  void sphere::
  type (const type_optional& x)
  {
    this->type_ = x;
  }


  // particle
  //

  const particle::location_type& particle::
  location () const
  {
    return this->location_.get ();
  }

  particle::location_type& particle::
  location ()
  {
    return this->location_.get ();
  }

  void particle::
  location (const location_type& x)
  {
    this->location_.set (x);
  }

  void particle::
  location (::std::auto_ptr< location_type > x)
  {
    this->location_.set (x);
  }

  const particle::velocity_type& particle::
  velocity () const
  {
    return this->velocity_.get ();
  }

  particle::velocity_type& particle::
  velocity ()
  {
    return this->velocity_.get ();
  }

  void particle::
  velocity (const velocity_type& x)
  {
    this->velocity_.set (x);
  }

  void particle::
  velocity (::std::auto_ptr< velocity_type > x)
  {
    this->velocity_.set (x);
  }

  const particle::mass_type& particle::
  mass () const
  {
    return this->mass_.get ();
  }

  particle::mass_type& particle::
  mass ()
  {
    return this->mass_.get ();
  }

  void particle::
  mass (const mass_type& x)
  {
    this->mass_.set (x);
  }

  const particle::type_optional& particle::
  type () const
  {
    return this->type_;
  }

  particle::type_optional& particle::
  type ()
  {
    return this->type_;
  }

  void particle::
  type (const type_type& x)
  {
    this->type_.set (x);
  }

  void particle::
  type (const type_optional& x)
  {
    this->type_ = x;
  }


  // type
  //

  const type::id_type& type::
  id () const
  {
    return this->id_.get ();
  }

  type::id_type& type::
  id ()
  {
    return this->id_.get ();
  }

  void type::
  id (const id_type& x)
  {
    this->id_.set (x);
  }

  const type::sigma_type& type::
  sigma () const
  {
    return this->sigma_.get ();
  }

  type::sigma_type& type::
  sigma ()
  {
    return this->sigma_.get ();
  }

  void type::
  sigma (const sigma_type& x)
  {
    this->sigma_.set (x);
  }

  const type::epsilon_type& type::
  epsilon () const
  {
    return this->epsilon_.get ();
  }

  type::epsilon_type& type::
  epsilon ()
  {
    return this->epsilon_.get ();
  }

  void type::
  epsilon (const epsilon_type& x)
  {
    this->epsilon_.set (x);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace input
{
  // decimalvector
  //

  decimalvector::
  decimalvector (const x_type& x,
                 const y_type& y,
                 const z_type& z)
  : ::xml_schema::type (),
    x_ (x, this),
    y_ (y, this),
    z_ (z, this)
  {
  }

  decimalvector::
  decimalvector (const decimalvector& x,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    x_ (x.x_, f, this),
    y_ (x.y_, f, this),
    z_ (x.z_, f, this)
  {
  }

  decimalvector::
  decimalvector (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    x_ (this),
    y_ (this),
    z_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
      this->parse (p, f);
    }
  }

  void decimalvector::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "x" && n.namespace_ ().empty ())
      {
        this->x_.set (x_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "y" && n.namespace_ ().empty ())
      {
        this->y_.set (y_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "z" && n.namespace_ ().empty ())
      {
        this->z_.set (z_traits::create (i, f, this));
        continue;
      }
    }

    if (!x_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "x",
        "");
    }

    if (!y_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "y",
        "");
    }

    if (!z_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "z",
        "");
    }
  }

  decimalvector* decimalvector::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class decimalvector (*this, f, c);
  }

  decimalvector& decimalvector::
  operator= (const decimalvector& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->x_ = x.x_;
      this->y_ = x.y_;
      this->z_ = x.z_;
    }

    return *this;
  }

  decimalvector::
  ~decimalvector ()
  {
  }

  // integervector
  //

  integervector::
  integervector (const x_type& x,
                 const y_type& y,
                 const z_type& z)
  : ::xml_schema::type (),
    x_ (x, this),
    y_ (y, this),
    z_ (z, this)
  {
  }

  integervector::
  integervector (const integervector& x,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    x_ (x.x_, f, this),
    y_ (x.y_, f, this),
    z_ (x.z_, f, this)
  {
  }

  integervector::
  integervector (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    x_ (this),
    y_ (this),
    z_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
      this->parse (p, f);
    }
  }

  void integervector::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "x" && n.namespace_ ().empty ())
      {
        this->x_.set (x_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "y" && n.namespace_ ().empty ())
      {
        this->y_.set (y_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "z" && n.namespace_ ().empty ())
      {
        this->z_.set (z_traits::create (i, f, this));
        continue;
      }
    }

    if (!x_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "x",
        "");
    }

    if (!y_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "y",
        "");
    }

    if (!z_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "z",
        "");
    }
  }

  integervector* integervector::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class integervector (*this, f, c);
  }

  integervector& integervector::
  operator= (const integervector& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->x_ = x.x_;
      this->y_ = x.y_;
      this->z_ = x.z_;
    }

    return *this;
  }

  integervector::
  ~integervector ()
  {
  }

  // boundarytype
  //

  boundarytype::
  boundarytype (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::string (e, f, c)
  {
    _xsd_boundarytype_convert ();
  }

  boundarytype::
  boundarytype (const ::xercesc::DOMAttr& a,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::string (a, f, c)
  {
    _xsd_boundarytype_convert ();
  }

  boundarytype::
  boundarytype (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::string (s, e, f, c)
  {
    _xsd_boundarytype_convert ();
  }

  boundarytype* boundarytype::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class boundarytype (*this, f, c);
  }

  boundarytype::value boundarytype::
  _xsd_boundarytype_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_boundarytype_literals_);
    const value* i (::std::lower_bound (
                      _xsd_boundarytype_indexes_,
                      _xsd_boundarytype_indexes_ + 3,
                      *this,
                      c));

    if (i == _xsd_boundarytype_indexes_ + 3 || _xsd_boundarytype_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const boundarytype::
  _xsd_boundarytype_literals_[3] =
  {
    "outflow",
    "reflecting",
    "periodic"
  };

  const boundarytype::value boundarytype::
  _xsd_boundarytype_indexes_[3] =
  {
    ::input::boundarytype::outflow,
    ::input::boundarytype::periodic,
    ::input::boundarytype::reflecting
  };

  // molsimdata
  //

  molsimdata::
  molsimdata (const outputbasename_type& outputbasename,
              const writefreq_type& writefreq,
              const timestep_type& timestep,
              const endtime_type& endtime,
              const thermostat_type& thermostat,
              const objectlist_type& objectlist,
              const particleTypes_type& particleTypes)
  : ::xml_schema::type (),
    outputbasename_ (outputbasename, this),
    writefreq_ (writefreq, this),
    timestep_ (timestep, this),
    endtime_ (endtime, this),
    domain_ (this),
    thermostat_ (thermostat, this),
    objectlist_ (objectlist, this),
    particleTypes_ (particleTypes, this)
  {
  }

  molsimdata::
  molsimdata (const outputbasename_type& outputbasename,
              const writefreq_type& writefreq,
              const timestep_type& timestep,
              const endtime_type& endtime,
              ::std::auto_ptr< thermostat_type > thermostat,
              ::std::auto_ptr< objectlist_type > objectlist,
              ::std::auto_ptr< particleTypes_type > particleTypes)
  : ::xml_schema::type (),
    outputbasename_ (outputbasename, this),
    writefreq_ (writefreq, this),
    timestep_ (timestep, this),
    endtime_ (endtime, this),
    domain_ (this),
    thermostat_ (thermostat, this),
    objectlist_ (objectlist, this),
    particleTypes_ (particleTypes, this)
  {
  }

  molsimdata::
  molsimdata (const molsimdata& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    outputbasename_ (x.outputbasename_, f, this),
    writefreq_ (x.writefreq_, f, this),
    timestep_ (x.timestep_, f, this),
    endtime_ (x.endtime_, f, this),
    domain_ (x.domain_, f, this),
    thermostat_ (x.thermostat_, f, this),
    objectlist_ (x.objectlist_, f, this),
    particleTypes_ (x.particleTypes_, f, this)
  {
  }

  molsimdata::
  molsimdata (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    outputbasename_ (this),
    writefreq_ (this),
    timestep_ (this),
    endtime_ (this),
    domain_ (this),
    thermostat_ (this),
    objectlist_ (this),
    particleTypes_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void molsimdata::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // outputbasename
      //
      if (n.name () == "outputbasename" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< outputbasename_type > r (
          outputbasename_traits::create (i, f, this));

        if (!outputbasename_.present ())
        {
          this->outputbasename_.set (r);
          continue;
        }
      }

      // writefreq
      //
      if (n.name () == "writefreq" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!writefreq_.present ())
        {
          this->writefreq_.set (writefreq_traits::create (i, f, this));
          continue;
        }
      }

      // timestep
      //
      if (n.name () == "timestep" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!timestep_.present ())
        {
          this->timestep_.set (timestep_traits::create (i, f, this));
          continue;
        }
      }

      // endtime
      //
      if (n.name () == "endtime" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!endtime_.present ())
        {
          this->endtime_.set (endtime_traits::create (i, f, this));
          continue;
        }
      }

      // domain
      //
      if (n.name () == "domain" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< domain_type > r (
          domain_traits::create (i, f, this));

        if (!this->domain_)
        {
          this->domain_.set (r);
          continue;
        }
      }

      // thermostat
      //
      if (n.name () == "thermostat" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< thermostat_type > r (
          thermostat_traits::create (i, f, this));

        if (!thermostat_.present ())
        {
          this->thermostat_.set (r);
          continue;
        }
      }

      // objectlist
      //
      if (n.name () == "objectlist" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< objectlist_type > r (
          objectlist_traits::create (i, f, this));

        if (!objectlist_.present ())
        {
          this->objectlist_.set (r);
          continue;
        }
      }

      // particleTypes
      //
      if (n.name () == "particleTypes" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< particleTypes_type > r (
          particleTypes_traits::create (i, f, this));

        if (!particleTypes_.present ())
        {
          this->particleTypes_.set (r);
          continue;
        }
      }

      break;
    }

    if (!outputbasename_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "outputbasename",
        "http://www.example.org/input");
    }

    if (!writefreq_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "writefreq",
        "http://www.example.org/input");
    }

    if (!timestep_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "timestep",
        "http://www.example.org/input");
    }

    if (!endtime_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "endtime",
        "http://www.example.org/input");
    }

    if (!thermostat_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "thermostat",
        "http://www.example.org/input");
    }

    if (!objectlist_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "objectlist",
        "http://www.example.org/input");
    }

    if (!particleTypes_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "particleTypes",
        "http://www.example.org/input");
    }
  }

  molsimdata* molsimdata::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class molsimdata (*this, f, c);
  }

  molsimdata& molsimdata::
  operator= (const molsimdata& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->outputbasename_ = x.outputbasename_;
      this->writefreq_ = x.writefreq_;
      this->timestep_ = x.timestep_;
      this->endtime_ = x.endtime_;
      this->domain_ = x.domain_;
      this->thermostat_ = x.thermostat_;
      this->objectlist_ = x.objectlist_;
      this->particleTypes_ = x.particleTypes_;
    }

    return *this;
  }

  molsimdata::
  ~molsimdata ()
  {
  }

  // domain
  //

  domain::
  domain (const size_type& size,
          const cutoff_type& cutoff,
          const boundaries_type& boundaries)
  : ::xml_schema::type (),
    size_ (size, this),
    cutoff_ (cutoff, this),
    boundaries_ (boundaries, this)
  {
  }

  domain::
  domain (::std::auto_ptr< size_type > size,
          const cutoff_type& cutoff,
          ::std::auto_ptr< boundaries_type > boundaries)
  : ::xml_schema::type (),
    size_ (size, this),
    cutoff_ (cutoff, this),
    boundaries_ (boundaries, this)
  {
  }

  domain::
  domain (const domain& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    size_ (x.size_, f, this),
    cutoff_ (x.cutoff_, f, this),
    boundaries_ (x.boundaries_, f, this)
  {
  }

  domain::
  domain (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    size_ (this),
    cutoff_ (this),
    boundaries_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void domain::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // size
      //
      if (n.name () == "size" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< size_type > r (
          size_traits::create (i, f, this));

        if (!size_.present ())
        {
          this->size_.set (r);
          continue;
        }
      }

      // cutoff
      //
      if (n.name () == "cutoff" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!cutoff_.present ())
        {
          this->cutoff_.set (cutoff_traits::create (i, f, this));
          continue;
        }
      }

      // boundaries
      //
      if (n.name () == "boundaries" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< boundaries_type > r (
          boundaries_traits::create (i, f, this));

        if (!boundaries_.present ())
        {
          this->boundaries_.set (r);
          continue;
        }
      }

      break;
    }

    if (!size_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "size",
        "http://www.example.org/input");
    }

    if (!cutoff_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "cutoff",
        "http://www.example.org/input");
    }

    if (!boundaries_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "boundaries",
        "http://www.example.org/input");
    }
  }

  domain* domain::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class domain (*this, f, c);
  }

  domain& domain::
  operator= (const domain& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->size_ = x.size_;
      this->cutoff_ = x.cutoff_;
      this->boundaries_ = x.boundaries_;
    }

    return *this;
  }

  domain::
  ~domain ()
  {
  }

  // thermostat
  //

  thermostat::
  thermostat (const inittemp_type& inittemp,
              const starttime_type& starttime,
              const targettemp_type& targettemp,
              const tempdiff_type& tempdiff,
              const interval_type& interval)
  : ::xml_schema::type (),
    brownian_ (this),
    inittemp_ (inittemp, this),
    starttime_ (starttime, this),
    targettemp_ (targettemp, this),
    tempdiff_ (tempdiff, this),
    interval_ (interval, this)
  {
  }

  thermostat::
  thermostat (const thermostat& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    brownian_ (x.brownian_, f, this),
    inittemp_ (x.inittemp_, f, this),
    starttime_ (x.starttime_, f, this),
    targettemp_ (x.targettemp_, f, this),
    tempdiff_ (x.tempdiff_, f, this),
    interval_ (x.interval_, f, this)
  {
  }

  thermostat::
  thermostat (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    brownian_ (this),
    inittemp_ (this),
    starttime_ (this),
    targettemp_ (this),
    tempdiff_ (this),
    interval_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void thermostat::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // brownian
      //
      if (n.name () == "brownian" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!this->brownian_)
        {
          this->brownian_.set (brownian_traits::create (i, f, this));
          continue;
        }
      }

      // inittemp
      //
      if (n.name () == "inittemp" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!inittemp_.present ())
        {
          this->inittemp_.set (inittemp_traits::create (i, f, this));
          continue;
        }
      }

      // starttime
      //
      if (n.name () == "starttime" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!starttime_.present ())
        {
          this->starttime_.set (starttime_traits::create (i, f, this));
          continue;
        }
      }

      // targettemp
      //
      if (n.name () == "targettemp" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!targettemp_.present ())
        {
          this->targettemp_.set (targettemp_traits::create (i, f, this));
          continue;
        }
      }

      // tempdiff
      //
      if (n.name () == "tempdiff" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!tempdiff_.present ())
        {
          this->tempdiff_.set (tempdiff_traits::create (i, f, this));
          continue;
        }
      }

      // interval
      //
      if (n.name () == "interval" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!interval_.present ())
        {
          this->interval_.set (interval_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!inittemp_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "inittemp",
        "http://www.example.org/input");
    }

    if (!starttime_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "starttime",
        "http://www.example.org/input");
    }

    if (!targettemp_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "targettemp",
        "http://www.example.org/input");
    }

    if (!tempdiff_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "tempdiff",
        "http://www.example.org/input");
    }

    if (!interval_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "interval",
        "http://www.example.org/input");
    }
  }

  thermostat* thermostat::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class thermostat (*this, f, c);
  }

  thermostat& thermostat::
  operator= (const thermostat& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->brownian_ = x.brownian_;
      this->inittemp_ = x.inittemp_;
      this->starttime_ = x.starttime_;
      this->targettemp_ = x.targettemp_;
      this->tempdiff_ = x.tempdiff_;
      this->interval_ = x.interval_;
    }

    return *this;
  }

  thermostat::
  ~thermostat ()
  {
  }

  // objectlist
  //

  objectlist::
  objectlist ()
  : ::xml_schema::type (),
    cuboid_ (this),
    sphere_ (this),
    particle_ (this)
  {
  }

  objectlist::
  objectlist (const objectlist& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    cuboid_ (x.cuboid_, f, this),
    sphere_ (x.sphere_, f, this),
    particle_ (x.particle_, f, this)
  {
  }

  objectlist::
  objectlist (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    cuboid_ (this),
    sphere_ (this),
    particle_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void objectlist::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // cuboid
      //
      if (n.name () == "cuboid" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< cuboid_type > r (
          cuboid_traits::create (i, f, this));

        this->cuboid_.push_back (r);
        continue;
      }

      // sphere
      //
      if (n.name () == "sphere" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< sphere_type > r (
          sphere_traits::create (i, f, this));

        this->sphere_.push_back (r);
        continue;
      }

      // particle
      //
      if (n.name () == "particle" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< particle_type > r (
          particle_traits::create (i, f, this));

        this->particle_.push_back (r);
        continue;
      }

      break;
    }
  }

  objectlist* objectlist::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class objectlist (*this, f, c);
  }

  objectlist& objectlist::
  operator= (const objectlist& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->cuboid_ = x.cuboid_;
      this->sphere_ = x.sphere_;
      this->particle_ = x.particle_;
    }

    return *this;
  }

  objectlist::
  ~objectlist ()
  {
  }

  // particleTypes
  //

  particleTypes::
  particleTypes ()
  : ::xml_schema::type (),
    type_ (this)
  {
  }

  particleTypes::
  particleTypes (const particleTypes& x,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    type_ (x.type_, f, this)
  {
  }

  particleTypes::
  particleTypes (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    type_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void particleTypes::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // type
      //
      if (n.name () == "type" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< type_type > r (
          type_traits::create (i, f, this));

        this->type_.push_back (r);
        continue;
      }

      break;
    }
  }

  particleTypes* particleTypes::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class particleTypes (*this, f, c);
  }

  particleTypes& particleTypes::
  operator= (const particleTypes& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->type_ = x.type_;
    }

    return *this;
  }

  particleTypes::
  ~particleTypes ()
  {
  }

  // boundaries
  //

  boundaries::
  boundaries (const front_type& front,
              const back_type& back,
              const left_type& left,
              const right_type& right,
              const top_type& top,
              const bottom_type& bottom)
  : ::xml_schema::type (),
    front_ (front, this),
    back_ (back, this),
    left_ (left, this),
    right_ (right, this),
    top_ (top, this),
    bottom_ (bottom, this)
  {
  }

  boundaries::
  boundaries (const boundaries& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    front_ (x.front_, f, this),
    back_ (x.back_, f, this),
    left_ (x.left_, f, this),
    right_ (x.right_, f, this),
    top_ (x.top_, f, this),
    bottom_ (x.bottom_, f, this)
  {
  }

  boundaries::
  boundaries (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    front_ (this),
    back_ (this),
    left_ (this),
    right_ (this),
    top_ (this),
    bottom_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void boundaries::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // front
      //
      if (n.name () == "front" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< front_type > r (
          front_traits::create (i, f, this));

        if (!front_.present ())
        {
          this->front_.set (r);
          continue;
        }
      }

      // back
      //
      if (n.name () == "back" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< back_type > r (
          back_traits::create (i, f, this));

        if (!back_.present ())
        {
          this->back_.set (r);
          continue;
        }
      }

      // left
      //
      if (n.name () == "left" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< left_type > r (
          left_traits::create (i, f, this));

        if (!left_.present ())
        {
          this->left_.set (r);
          continue;
        }
      }

      // right
      //
      if (n.name () == "right" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< right_type > r (
          right_traits::create (i, f, this));

        if (!right_.present ())
        {
          this->right_.set (r);
          continue;
        }
      }

      // top
      //
      if (n.name () == "top" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< top_type > r (
          top_traits::create (i, f, this));

        if (!top_.present ())
        {
          this->top_.set (r);
          continue;
        }
      }

      // bottom
      //
      if (n.name () == "bottom" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< bottom_type > r (
          bottom_traits::create (i, f, this));

        if (!bottom_.present ())
        {
          this->bottom_.set (r);
          continue;
        }
      }

      break;
    }

    if (!front_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "front",
        "http://www.example.org/input");
    }

    if (!back_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "back",
        "http://www.example.org/input");
    }

    if (!left_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "left",
        "http://www.example.org/input");
    }

    if (!right_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "right",
        "http://www.example.org/input");
    }

    if (!top_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "top",
        "http://www.example.org/input");
    }

    if (!bottom_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "bottom",
        "http://www.example.org/input");
    }
  }

  boundaries* boundaries::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class boundaries (*this, f, c);
  }

  boundaries& boundaries::
  operator= (const boundaries& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->front_ = x.front_;
      this->back_ = x.back_;
      this->left_ = x.left_;
      this->right_ = x.right_;
      this->top_ = x.top_;
      this->bottom_ = x.bottom_;
    }

    return *this;
  }

  boundaries::
  ~boundaries ()
  {
  }

  // cuboid
  //

  cuboid::
  cuboid (const location_type& location,
          const velocity_type& velocity,
          const numparticles_type& numparticles,
          const meshwidth_type& meshwidth,
          const mass_type& mass)
  : ::xml_schema::type (),
    location_ (location, this),
    velocity_ (velocity, this),
    numparticles_ (numparticles, this),
    meshwidth_ (meshwidth, this),
    mass_ (mass, this),
    type_ (this)
  {
  }

  cuboid::
  cuboid (::std::auto_ptr< location_type > location,
          ::std::auto_ptr< velocity_type > velocity,
          ::std::auto_ptr< numparticles_type > numparticles,
          const meshwidth_type& meshwidth,
          const mass_type& mass)
  : ::xml_schema::type (),
    location_ (location, this),
    velocity_ (velocity, this),
    numparticles_ (numparticles, this),
    meshwidth_ (meshwidth, this),
    mass_ (mass, this),
    type_ (this)
  {
  }

  cuboid::
  cuboid (const cuboid& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    location_ (x.location_, f, this),
    velocity_ (x.velocity_, f, this),
    numparticles_ (x.numparticles_, f, this),
    meshwidth_ (x.meshwidth_, f, this),
    mass_ (x.mass_, f, this),
    type_ (x.type_, f, this)
  {
  }

  cuboid::
  cuboid (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    location_ (this),
    velocity_ (this),
    numparticles_ (this),
    meshwidth_ (this),
    mass_ (this),
    type_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void cuboid::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // location
      //
      if (n.name () == "location" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< location_type > r (
          location_traits::create (i, f, this));

        if (!location_.present ())
        {
          this->location_.set (r);
          continue;
        }
      }

      // velocity
      //
      if (n.name () == "velocity" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< velocity_type > r (
          velocity_traits::create (i, f, this));

        if (!velocity_.present ())
        {
          this->velocity_.set (r);
          continue;
        }
      }

      // numparticles
      //
      if (n.name () == "numparticles" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< numparticles_type > r (
          numparticles_traits::create (i, f, this));

        if (!numparticles_.present ())
        {
          this->numparticles_.set (r);
          continue;
        }
      }

      // meshwidth
      //
      if (n.name () == "meshwidth" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!meshwidth_.present ())
        {
          this->meshwidth_.set (meshwidth_traits::create (i, f, this));
          continue;
        }
      }

      // mass
      //
      if (n.name () == "mass" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!mass_.present ())
        {
          this->mass_.set (mass_traits::create (i, f, this));
          continue;
        }
      }

      // type
      //
      if (n.name () == "type" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!this->type_)
        {
          this->type_.set (type_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!location_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "location",
        "http://www.example.org/input");
    }

    if (!velocity_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "velocity",
        "http://www.example.org/input");
    }

    if (!numparticles_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "numparticles",
        "http://www.example.org/input");
    }

    if (!meshwidth_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "meshwidth",
        "http://www.example.org/input");
    }

    if (!mass_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "mass",
        "http://www.example.org/input");
    }
  }

  cuboid* cuboid::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class cuboid (*this, f, c);
  }

  cuboid& cuboid::
  operator= (const cuboid& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->location_ = x.location_;
      this->velocity_ = x.velocity_;
      this->numparticles_ = x.numparticles_;
      this->meshwidth_ = x.meshwidth_;
      this->mass_ = x.mass_;
      this->type_ = x.type_;
    }

    return *this;
  }

  cuboid::
  ~cuboid ()
  {
  }

  // sphere
  //

  sphere::
  sphere (const location_type& location,
          const velocity_type& velocity,
          const numparticles_type& numparticles,
          const meshwidth_type& meshwidth,
          const mass_type& mass,
          const sigma_type& sigma,
          const epsilon_type& epsilon)
  : ::xml_schema::type (),
    location_ (location, this),
    velocity_ (velocity, this),
    numparticles_ (numparticles, this),
    meshwidth_ (meshwidth, this),
    mass_ (mass, this),
    sigma_ (sigma, this),
    epsilon_ (epsilon, this),
    type_ (this)
  {
  }

  sphere::
  sphere (::std::auto_ptr< location_type > location,
          ::std::auto_ptr< velocity_type > velocity,
          const numparticles_type& numparticles,
          const meshwidth_type& meshwidth,
          const mass_type& mass,
          const sigma_type& sigma,
          const epsilon_type& epsilon)
  : ::xml_schema::type (),
    location_ (location, this),
    velocity_ (velocity, this),
    numparticles_ (numparticles, this),
    meshwidth_ (meshwidth, this),
    mass_ (mass, this),
    sigma_ (sigma, this),
    epsilon_ (epsilon, this),
    type_ (this)
  {
  }

  sphere::
  sphere (const sphere& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    location_ (x.location_, f, this),
    velocity_ (x.velocity_, f, this),
    numparticles_ (x.numparticles_, f, this),
    meshwidth_ (x.meshwidth_, f, this),
    mass_ (x.mass_, f, this),
    sigma_ (x.sigma_, f, this),
    epsilon_ (x.epsilon_, f, this),
    type_ (x.type_, f, this)
  {
  }

  sphere::
  sphere (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    location_ (this),
    velocity_ (this),
    numparticles_ (this),
    meshwidth_ (this),
    mass_ (this),
    sigma_ (this),
    epsilon_ (this),
    type_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void sphere::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // location
      //
      if (n.name () == "location" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< location_type > r (
          location_traits::create (i, f, this));

        if (!location_.present ())
        {
          this->location_.set (r);
          continue;
        }
      }

      // velocity
      //
      if (n.name () == "velocity" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< velocity_type > r (
          velocity_traits::create (i, f, this));

        if (!velocity_.present ())
        {
          this->velocity_.set (r);
          continue;
        }
      }

      // numparticles
      //
      if (n.name () == "numparticles" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!numparticles_.present ())
        {
          this->numparticles_.set (numparticles_traits::create (i, f, this));
          continue;
        }
      }

      // meshwidth
      //
      if (n.name () == "meshwidth" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!meshwidth_.present ())
        {
          this->meshwidth_.set (meshwidth_traits::create (i, f, this));
          continue;
        }
      }

      // mass
      //
      if (n.name () == "mass" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!mass_.present ())
        {
          this->mass_.set (mass_traits::create (i, f, this));
          continue;
        }
      }

      // sigma
      //
      if (n.name () == "sigma" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!sigma_.present ())
        {
          this->sigma_.set (sigma_traits::create (i, f, this));
          continue;
        }
      }

      // epsilon
      //
      if (n.name () == "epsilon" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!epsilon_.present ())
        {
          this->epsilon_.set (epsilon_traits::create (i, f, this));
          continue;
        }
      }

      // type
      //
      if (n.name () == "type" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!this->type_)
        {
          this->type_.set (type_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!location_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "location",
        "http://www.example.org/input");
    }

    if (!velocity_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "velocity",
        "http://www.example.org/input");
    }

    if (!numparticles_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "numparticles",
        "http://www.example.org/input");
    }

    if (!meshwidth_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "meshwidth",
        "http://www.example.org/input");
    }

    if (!mass_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "mass",
        "http://www.example.org/input");
    }

    if (!sigma_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "sigma",
        "http://www.example.org/input");
    }

    if (!epsilon_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "epsilon",
        "http://www.example.org/input");
    }
  }

  sphere* sphere::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class sphere (*this, f, c);
  }

  sphere& sphere::
  operator= (const sphere& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->location_ = x.location_;
      this->velocity_ = x.velocity_;
      this->numparticles_ = x.numparticles_;
      this->meshwidth_ = x.meshwidth_;
      this->mass_ = x.mass_;
      this->sigma_ = x.sigma_;
      this->epsilon_ = x.epsilon_;
      this->type_ = x.type_;
    }

    return *this;
  }

  sphere::
  ~sphere ()
  {
  }

  // particle
  //

  particle::
  particle (const location_type& location,
            const velocity_type& velocity,
            const mass_type& mass)
  : ::xml_schema::type (),
    location_ (location, this),
    velocity_ (velocity, this),
    mass_ (mass, this),
    type_ (this)
  {
  }

  particle::
  particle (::std::auto_ptr< location_type > location,
            ::std::auto_ptr< velocity_type > velocity,
            const mass_type& mass)
  : ::xml_schema::type (),
    location_ (location, this),
    velocity_ (velocity, this),
    mass_ (mass, this),
    type_ (this)
  {
  }

  particle::
  particle (const particle& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    location_ (x.location_, f, this),
    velocity_ (x.velocity_, f, this),
    mass_ (x.mass_, f, this),
    type_ (x.type_, f, this)
  {
  }

  particle::
  particle (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    location_ (this),
    velocity_ (this),
    mass_ (this),
    type_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void particle::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // location
      //
      if (n.name () == "location" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< location_type > r (
          location_traits::create (i, f, this));

        if (!location_.present ())
        {
          this->location_.set (r);
          continue;
        }
      }

      // velocity
      //
      if (n.name () == "velocity" && n.namespace_ () == "http://www.example.org/input")
      {
        ::std::auto_ptr< velocity_type > r (
          velocity_traits::create (i, f, this));

        if (!velocity_.present ())
        {
          this->velocity_.set (r);
          continue;
        }
      }

      // mass
      //
      if (n.name () == "mass" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!mass_.present ())
        {
          this->mass_.set (mass_traits::create (i, f, this));
          continue;
        }
      }

      // type
      //
      if (n.name () == "type" && n.namespace_ () == "http://www.example.org/input")
      {
        if (!this->type_)
        {
          this->type_.set (type_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!location_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "location",
        "http://www.example.org/input");
    }

    if (!velocity_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "velocity",
        "http://www.example.org/input");
    }

    if (!mass_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "mass",
        "http://www.example.org/input");
    }
  }

  particle* particle::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class particle (*this, f, c);
  }

  particle& particle::
  operator= (const particle& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->location_ = x.location_;
      this->velocity_ = x.velocity_;
      this->mass_ = x.mass_;
      this->type_ = x.type_;
    }

    return *this;
  }

  particle::
  ~particle ()
  {
  }

  // type
  //

  type::
  type (const id_type& id,
        const sigma_type& sigma,
        const epsilon_type& epsilon)
  : ::xml_schema::type (),
    id_ (id, this),
    sigma_ (sigma, this),
    epsilon_ (epsilon, this)
  {
  }

  type::
  type (const type& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    id_ (x.id_, f, this),
    sigma_ (x.sigma_, f, this),
    epsilon_ (x.epsilon_, f, this)
  {
  }

  type::
  type (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    id_ (this),
    sigma_ (this),
    epsilon_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
      this->parse (p, f);
    }
  }

  void type::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "id" && n.namespace_ ().empty ())
      {
        this->id_.set (id_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "sigma" && n.namespace_ ().empty ())
      {
        this->sigma_.set (sigma_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "epsilon" && n.namespace_ ().empty ())
      {
        this->epsilon_.set (epsilon_traits::create (i, f, this));
        continue;
      }
    }

    if (!id_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "id",
        "");
    }

    if (!sigma_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "sigma",
        "");
    }

    if (!epsilon_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "epsilon",
        "");
    }
  }

  type* type::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class type (*this, f, c);
  }

  type& type::
  operator= (const type& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->id_ = x.id_;
      this->sigma_ = x.sigma_;
      this->epsilon_ = x.epsilon_;
    }

    return *this;
  }

  type::
  ~type ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace input
{
  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (const ::std::string& u,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::auto_ptr< ::input::molsimdata > (
      ::input::molsimdata_ (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (const ::std::string& u,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::input::molsimdata > (
      ::input::molsimdata_ (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (const ::std::string& u,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::input::molsimdata > (
      ::input::molsimdata_ (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::std::istream& is,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::input::molsimdata_ (isrc, f, p);
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::std::istream& is,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::input::molsimdata_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::std::istream& is,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::input::molsimdata_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::std::istream& is,
               const ::std::string& sid,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::input::molsimdata_ (isrc, f, p);
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::std::istream& is,
               const ::std::string& sid,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::input::molsimdata_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::std::istream& is,
               const ::std::string& sid,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::input::molsimdata_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::xercesc::InputSource& i,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::auto_ptr< ::input::molsimdata > (
      ::input::molsimdata_ (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::xercesc::InputSource& i,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::input::molsimdata > (
      ::input::molsimdata_ (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::xercesc::InputSource& i,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::input::molsimdata > (
      ::input::molsimdata_ (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (const ::xercesc::DOMDocument& doc,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

      return ::std::auto_ptr< ::input::molsimdata > (
        ::input::molsimdata_ (
          d, f | ::xml_schema::flags::own_dom, p));
    }

    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "molsimdata" &&
        n.namespace_ () == "http://www.example.org/input")
    {
      ::std::auto_ptr< ::input::molsimdata > r (
        ::xsd::cxx::tree::traits< ::input::molsimdata, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "molsimdata",
      "http://www.example.org/input");
  }

  ::std::auto_ptr< ::input::molsimdata >
  molsimdata_ (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
               ::xml_schema::flags f,
               const ::xml_schema::properties&)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "molsimdata" &&
        n.namespace_ () == "http://www.example.org/input")
    {
      ::std::auto_ptr< ::input::molsimdata > r (
        ::xsd::cxx::tree::traits< ::input::molsimdata, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "molsimdata",
      "http://www.example.org/input");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

